### ISSUE TITLE
وجود دو متد همنام get_user_usage در یک کلاس

### ISSUE THREAD

**Issue by AmirKenzo** [sm1ky/marzban_api#10]
سلام،
من هنگام استفاده از کتابخانه شما متوجه شدم که در یک کلاس دو متد با نام یکسان get_user_usage تعریف شده‌اند

متد اول: خط 249
متد دوم: خط 356

**Comment by sm1ky** [comment]
Hello, thank you for bringing that error to my attention. I have fixed it in the [new commit](https://github.com/sm1ky/marzban_api/commit/250f638861f5b02e6d254f21bfdfe6fd08cbbb66)
